# Generated by Django 5.0.2 on 2025-10-09 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_movil_escolar_webapp_api', '0002_administradores_delete_profiles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administradores',
            old_name='claveAdmin',
            new_name='clave_admin',
        ),
    ]
