# Generated by Django 5.0.2 on 2025-10-15 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_movil_escolar_webapp_api', '0004_alumnos'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnos',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
