# Generated by Django 5.0.2 on 2025-10-16 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_movil_escolar_webapp_api', '0006_maestros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maestros',
            name='materias_json',
            field=models.JSONField(null=True),
        ),
    ]
