# Generated by Django 5.0.2 on 2025-11-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_movil_escolar_webapp_api', '0008_alter_maestros_materias_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materias',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nrc', models.CharField(max_length=20, unique=True)),
                ('nombre_materia', models.CharField(max_length=255)),
                ('seccion', models.CharField(blank=True, max_length=255, null=True)),
                ('dias_json', models.JSONField(blank=True, null=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('salon', models.CharField(blank=True, max_length=255, null=True)),
                ('programa_educativo', models.CharField(blank=True, max_length=255, null=True)),
                ('profesor_asignado', models.CharField(blank=True, max_length=255, null=True)),
                ('creditos', models.CharField(blank=True, max_length=255, null=True)),
                ('creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('update', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
